var config = {
  CLIENT_ID: 'XXXXXXXXXXXXX-XXXXXXXXXXXXXXXXXXXXXX.apps.googleusercontent.com',
  CLIENT_SECRET: 'XXXXXXX-XXXXXXXXXXXXXXXX',
  REFRESHTOKEN: 'X/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
}

module.exports = config
